// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyInvites.Models;

#nullable disable

namespace PartyInvites.Migrations
{
    [DbContext(typeof(InviteDbContext))]
    partial class InviteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartyInvites.Models.GuestResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WillAttend")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GuestResponses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Yian@gmail.com",
                            Name = "Yian-Garuga",
                            Phone = "0611202273",
                            WillAttend = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "Yian@gmail.com",
                            Name = "Tzitzi-ya-ku",
                            Phone = "0611202273",
                            WillAttend = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
